### ISSUE TITLE
/yog/upload报404错误

### ISSUE THREAD

**Issue by heimeixn** [fex-team/yog2#166]
这个问题出现好几次了，请问什么原因，怎么避免呢？

npm install时出现以下信息：
npm WARN package.json yog2@1.0.0 license should be a valid SPDX license expression
npm WARN deprecated swig@1.4.0: This package is no longer maintained

执行 yog2 release --dest debug时 出现以下信息：
Error: upload file [/client/components/bootstrap-datepicker/README.md] to [/] by receiver [http://127.0.0.1:8085/yog/upload] error [404]
    at Object.exports.error (/usr/local/lib/node_modules/yog2/node_modules/fis/node_modules/fis-kernel/lib/log.js:57:15)
    at /usr/local/lib/node_modules/yog2/node_modules/fis/node_modules/fis-deploy-default/index.js:230:25
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/yog2/node_modules/fis/node_modules/fis-kernel/lib/util.js:838:21)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)

**Comment by hefangshi** [comment]
YOG2没有以开发模式启动，就不会有这个部署路径。
