### ISSUE TITLE
yog2 基础demo 加载插件recv-reload报错

### ISSUE THREAD

**Issue by w4ngzhen** [fex-team/yog2#204]
在官方样例指南下，`yog2 init project`并安装依赖后，使用命令`yog2 run`无法启动，直接报错如下：
```
YOG/LOADER 19624: load plugin [recv-reload] with conf {"tarReceiverUrl":"/yog/uploadtar","cleanCacheUrl":"/yog/reload","receiverUrl":"/yog/upload","uploadTimeout":30,"maxTarSize":"200mb","lazyAppReload":false}
fs.js:36
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:36:5
    at req_ (D:\Projects\baidu-front\demo-simple\yog2-demo\node_modules\natives\index.js:143:24)
    at Object.req [as require] (D:\Projects\baidu-front\demo-simple\yog2-demo\node_modules\natives\index.js:55:10)
    at Object.<anonymous> (D:\Projects\baidu-front\demo-simple\yog2-demo\node_modules\graceful-fs\fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (D:\Projects\baidu-front\demo-simple\yog2-demo\node_modules\graceful-fs\graceful-fs.js:3:27)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```
yog2版本：
```
v1.6.0
```

**Comment by HereSinceres** [comment]
node 切换为10版本
