### ISSUE TITLE
yog2 init project 时报错

### ISSUE THREAD

**Issue by hongqi** [fex-team/yog2#23]
$: yog2 init app

 [NOTIC] Downloading and unzipping...
path.js:471
      throw new TypeError('Arguments to path.join must be strings');
      ^
TypeError: Arguments to path.join must be strings
    at Object.posix.join (path.js:471:13)
    at deploy (/usr/local/lib/node_modules/yog2/node_modules/yog2-command-init/index.js:110:36)
    at /usr/local/lib/node_modules/yog2/node_modules/yog2-command-init/index.js:104:17
    at Extract.<anonymous> (/usr/local/lib/node_modules/yog2/node_modules/yog2-command-init/node_modules/fis-scaffold-kernel/lib/util.js:262:33)
    at Extract.emit (events.js:129:20)
    at DirWriter.<anonymous> (/usr/local/lib/node_modules/yog2/node_modules/yog2-command-init/node_modules/fis-scaffold-kernel/node_modules/tar/lib/extract.js:74:8)
    at DirWriter.emit (events.js:129:20)
    at end (/usr/local/lib/node_modules/yog2/node_modules/yog2-command-init/node_modules/fis-scaffold-kernel/node_modules/tar/node_modules/fstream/lib/writer.js:324:14)
    at /usr/local/lib/node_modules/yog2/node_modules/yog2-command-init/node_modules/fis-scaffold-kernel/node_modules/tar/node_modules/fstream/lib/writer.js:314:34
    at endUtimes (/usr/local/lib/node_modules/yog2/node_modules/yog2-command-init/node_modules/fis-scaffold-kernel/node_modules/tar/node_modules/fstream/lib/writer.js:238:46)

**Comment by hefangshi** [comment]
可以再更新一下 yog2 试试看

```
npm i -g yog2
```

**Comment by hongqi** [comment]
嗯，好了！辛苦！
