### ISSUE TITLE
ES6 action bug？

### ISSUE THREAD

**Issue by rendongsc** [fex-team/yog2#49]
es6 action 函数如果加了默认参数值，报错！
const checkLoginFailLimit = function (name, callback = _.noop) {
    const key = `checkLoginFailCount_${ name }`;
    cache.get(key, (err, count) => {
        if (err) {
            return callback(err);
        }
        count = count || 0;
        callback(null, count > config.limit.login_fail.count);
    });
};
--------------------错误信息如下--------------------------------
SyntaxError: Unexpected token =
   at exports.runInThisContext (vm.js:53:16)
   at Module._compile (module.js:414:25)
   at Object.Module._extensions..js (module.js:442:10)
   at Module.load (module.js:356:32)
   at Function.Module._load (module.js:311:12)
   at Module.require (module.js:366:17)
   at require (module.js:385:17)
   at getAction (D:\App\node_modules\yog2-kernel\plugins\dispatcher\dispatcher.js:137:22)
   at Function.router.action (D:\App\node_modules\yog2-kernel\plugins\dispatcher\dispatcher.js:182:20)
   at module.exports (D:\App\app\home\router.js:15:33)
   at createActionRouter (D:\App\node_modules\yog2-kernel\plugins\dispatcher\dispatcher.js:187:9)
   at getRouter (D:\App\node_modules\yog2-kernel\plugins\dispatcher\dispatcher.js:104:22)
   at baseRouterHandler (D:\App\node_modules\yog2-kernel\plugins\dispatcher\dispatcher.js:32:22)
   at Layer.handle [as handle_request] (D:\App\node_modules\yog2-kernel\node_modules\express\lib\router\layer.js:95:5)
   at next (D:\App\node_modules\yog2-kernel\node_modules\express\lib\router\route.js:131:13)
   at Route.dispatch (D:\App\node_modules\yog2-kernel\node_modules\express\lib\router\route.js:112:3)
   at Layer.handle [as handle_request] (D:\App\node_modules\yog2-kernel\node_modules\express\lib\router\layer.js:95:5)
   at D:\App\node_modules\yog2-kernel\node_modules\express\lib\router\index.js:277:22
   at param (D:\App\node_modules\yog2-kernel\node_modules\express\lib\router\index.js:349:14)
   at param (D:\App\node_modules\yog2-kernel\node_modules\express\lib\router\index.js:365:14)
   at Function.process_params (D:\App\node_modules\yog2-kernel\node_modules\express\lib\router\index.js:410:3)
   at next (D:\App\node_modules\yog2-kernel\node_modules\express\lib\router\index.js:271:10)

**Comment by hefangshi** [comment]
yog2目前默认没有支持es6，如果需要使用的话，可以自行使用babel插件编译
