### ISSUE TITLE
运行报缺少debuglog模块

### ISSUE THREAD

**Issue by fancyboynet** [fex-team/yog2#8]
我是用的`yog2 init project`
`npm install`后 运行*app.js*,报下面的错误
```bash
/usr/local/bin/node app.js
module.js:338
    throw err;
          ^
Error: Cannot find module 'debuglog'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/xxx/yog2/yog/plugins/recv-reload/index.js:3:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

**Comment by hefangshi** [comment]
感谢反馈，最近一次调整不小心给删除了
